# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  AuraGL_config = debug
endif
ifeq ($(config),release)
  AuraGL_config = release
endif

PROJECTS := AuraGL

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

AuraGL:
ifneq (,$(AuraGL_config))
	@echo "==== Building AuraGL ($(AuraGL_config)) ===="
	@${MAKE} --no-print-directory -C . -f AuraGL.make config=$(AuraGL_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f AuraGL.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   AuraGL"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"