# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  AuraVK_config = debug
endif
ifeq ($(config),release)
  AuraVK_config = release
endif
ifeq ($(config),dist)
  AuraVK_config = dist
endif

PROJECTS := AuraVK

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

AuraVK:
ifneq (,$(AuraVK_config))
	@echo "==== Building AuraVK ($(AuraVK_config)) ===="
	@${MAKE} --no-print-directory -C . -f AuraVK.make config=$(AuraVK_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f AuraVK.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   AuraVK"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"